spring:
  application:
    name: electric-bill-service

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:local}
  prometheus:
    metrics:
      export:
        enabled: true

external-services:
  electricity-provider:
    url: http://toxiproxy:6000

server:
  port: 5000