spring:
  application:
    name: electric-bill-service

feign:
  client:
    config:
      default:
        connectTimeout: ${FEIGN_CONNECT_TIMEOUT:3000}
        readTimeout: ${FEIGN_READ_TIMEOUT:3000}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:local}
  prometheus:
    metrics:
      export:
        enabled: true

external-services:
  electricity-provider:
    url: ${EXTERNAL_PROVIDER_URL:http://toxiproxy:6000}

server:
  port: 5000