server:
  port: 5000

spring:
  application:
    name: electric-bill-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: ${FEIGN_CONNECT_TIMEOUT:3000}
            readTimeout: ${FEIGN_READ_TIMEOUT:3000}

external-services:
  electricity-provider:
    url: ${EXTERNAL_PROVIDER_URL:http://localhost:6000}
  payment-service:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8081}

#monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
        feign.client.requests: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:local}
    export:
      prometheus:
        enabled: true

# activa métricas Feign para Prometheus/Micrometer
feign:
  metrics:
    enabled: true

logging:
  level:
    feign: DEBUG
    feign.client: DEBUG
    org.springframework.cloud.openfeign: DEBUG

#circuit-breaker
resilience4j:
  enabled: ${R4J_ENABLED:true} # TODO: Establecer en true en entornos donde se desee activar Resilience4j
  circuit-breaker:
    instances:
      getBillDetails:
        register-health-indicator: ${CB_REGISTER_HEALTH_INDICATOR:true} # Expone métricas del Circuit Breaker a través del Actuator de Spring Boot
        # Estado cerrado (Closed)
        sliding-window-type: ${CB_SLIDING_WINDOW_TYPE:count_based} # Define el tipo de ventana para monitoreo: 'count_based' o 'time_based'
        sliding-window-size: ${CB_SLIDING_WINDOW_SIZE:10} # Número de últimas llamadas evaluadas cuando el Circuit Breaker está cerrado
        minimum-number-of-calls: ${CB_MINIMUM_NUMBER_OF_CALLS:5} # Número mínimo de llamadas necesarias antes de evaluar el porcentaje de fallas

        failure-rate-threshold: ${CB_FAILURE_RATE_THRESHOLD :50} # Porcentaje de fallas (50%) para abrir el Circuit Breaker
        slow-call-rate-threshold: ${CB_SLOW_CALL_RATE_THRESHOLD:100} # Porcentaje de llamadas lentas que deben alcanzarse para considerarlo una falla
        slow-call-duration-threshold: ${CB_SLOW_CALL_DURATION_THRESHOLD:60000} # Duración en milisegundos (60s) para considerar una llamada como lenta
        # Estado abierto (Open)
        wait-duration-in-open-state: ${CB_WAIT_DURATION_IN_OPEN_STATE:6000} # Tiempo (en milisegundos) que el CB permanece abierto antes de pasar a estado medio-abierto
        # Estado medio-abierto (Half-Open)
        permitted-number-of-calls-in-half-open-state: ${CB_PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE:5} # Número de llamadas permitidas para probar si el servicio se ha recuperado
        automatic-transition-from-open-to-half-open-enabled: ${CB_AUTOMATIC_TRANSITION_FROM_OPEN_TO_HALF_OPEN_ENABLED:true} # Habilita la transición automática del estado abierto al medio-abierto

