server:
  port: 9050

spring:
  application:
    name: payment-management-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: ${FEIGN_CONNECT_TIMEOUT:3000}
            readTimeout: ${FEIGN_READ_TIMEOUT:3000}

# Service URLs
account:
  service:
    url: ${ACCOUNT_SERVICE_URL:http://account-service:8080}

transaction:
  service:
    url: ${TRANSACTION_SERVICE_URL:http://transaction-service:8080}

internal-services:
  electric-bill-service:
    url: ${MICROSERVICE_ELECTRIC_BILL_URL:http://electric-bill-service:5000}

#monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:local}
  prometheus:
    metrics:
      export:
        enabled: true